mysite/cats/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = 'cats'

urlpatterns = [
    path("",views.CatListView.as_view(),name="cat-list"),
    path("main/create/",views.CatCreateView.as_view(),name="cat-create"),
    path("main/<int:pk>/update/",views.CatUpdateView.as_view(),name="cat-update"),
    path("main/<int:pk>/delete/",views.CatDeleteView.as_view(),name="cat-delete"),

    path("lookup/",views.BreedListView.as_view(),name="breed-list"),
    path("lookup/create/",views.BreedCreateView.as_view(),name="breed-create"),
    path("lookup/<int:pk>/update/",views.BreedUpdateView.as_view(),name="breed-update"),
    path("lookup/<int:pk>/delete/",views.BreedDeleteView.as_view(),name="breed-delete"),
    # path('', TemplateView.as_view(template_name='home/main.html')),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.views.static import serve

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')


urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/",include('polls.urls')),
    path("hello/",include('hello.urls')),
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('solo2/', include('solo2.urls')),
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),

]

mysite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator


# Create your models here.

class Cat(models.Model):
    nickname = models.CharField(max_length=200,validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")])
    weight = models.PositiveIntegerField()
    foods = models.TextField(max_length=300)
    breed = models.ForeignKey('Breed',on_delete=models.CASCADE,null=False)

    def __str__(self):
        return self.nickname

class Breed(models.Model):
    name = models.CharField(max_length=200,validators=[MinLengthValidator(2, "Breed must be greater than 1 character")])

    def __str__(self):
        return self.name

mysite/cats/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from cats.models import Cat, Breed

# Create your views here.
class CatListView(LoginRequiredMixin,ListView):
    model = Cat

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["breed_count"] = Breed.objects.count()
        return context

class CatCreateView(LoginRequiredMixin,CreateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:cat-list')

class CatUpdateView(LoginRequiredMixin,UpdateView):
    model = Cat
    fields = '__all__'
    # template_name_suffix = "_update_form"
    success_url = reverse_lazy('cats:cat-list')

class CatDeleteView(LoginRequiredMixin,DeleteView):
    model = Cat
    success_url = reverse_lazy('cats:cat-list')




class BreedListView(LoginRequiredMixin,ListView):
    model = Breed

class BreedCreateView(LoginRequiredMixin,CreateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:cat-list')

class BreedUpdateView(LoginRequiredMixin,UpdateView):
    model = Breed
    fields = '__all__'
    # template_name_suffix = "_update_form"
    success_url = reverse_lazy('cats:cat-list')

class BreedDeleteView(LoginRequiredMixin,DeleteView):
    model = Breed
    success_url = reverse_lazy('cats:cat-list')

mysite/cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %} {% block content %}

<h1>Delete Breed</h1>

<p>Are you sure you want to delete the breed: {{ breed }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
  <input
    type="submit"
    onclick="window.location='{% url 'cats:cat-list' %}' ; return false;"
    value="Cancel"
  />
</form>

{% endblock %}

mysite/cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %} {% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
  <input
    type="submit"
    onclick="window.location='{% url 'cats:cat-list' %}' ; return false;"
    value="Cancel"
  />
</form>
{% endblock %}

mysite/cats/templates/cats/breed_list.html
{% extends "base_bootstrap.html" %} {% block content %}
<h1>Breeds List</h1>
{% if breed_list %}
<ul>
  {% for breed in breed_list %}
  <li>
    {{ breed.name }} (<a href="{% url 'cats:breed-update' breed.id %}"
      >Update</a
    >
    | <a href="{% url 'cats:breed-delete' breed.id %}">Delete</a>)
  </li>
  {% endfor %}
</ul>
{% else %}
<p>There are no breeds in the library.</p>
{% endif %}
<p><a href="{% url 'cats:breed-create' %}">Add a breed</a></p>
<p>
  <a href="{% url 'cats:cat-list' %}">Back to cats</a>
</p>
{% endblock %}

mysite/cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %} {% block content %}

<h1>Delete Cat</h1>

<p>Are you sure you want to delete the cat: {{ cat }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

mysite/cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %} {% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
  <input
    type="submit"
    onclick="window.location='{% url 'cats:cat-list' %}' ; return false;"
    value="Cancel"
  />
</form>
{% endblock %}

mysite/cats/templates/cats/cat_list.html
{% extends "base_bootstrap.html" %} {% block content %}
<h1>Cats List</h1>
{% if cat_list %}
<ul>
  {% for cat in cat_list %}
  <li>
    {{ cat.nickname }} ({{ cat.breed }}) (<a
      href="{% url 'cats:cat-update' cat.id %}"
      >Update</a
    >
    | <a href="{% url 'cats:cat-delete' cat.id %}">Delete</a>) <br />
    {{ cat.foods }} ({{ cat.weight }} miles)
  </li>
  {% endfor %}
</ul>
{% else %}
<p>There are no cats in the library.</p>
{% endif %}
<p>
  {% if breed_count > 0 %}
  <a href="{% url 'cats:cat-create' %}">Add a cat</a>
  {% else %} Please add a breed before you add a cat. {% endif %}
</p>
<p>
  <a href="{% url 'cats:breed-list' %}">View breeds</a> ({{ breed_count }}) |
  <a href="{% url 'cats:breed-create' %}">Add a breed</a>
</p>
{% endblock %}